
import Print            from './Print';
import AddingNewTile    from './AddingNewTile';
import CheckIfCanMerge   from './CheckIfCanMerge';
import CloneMatrix      from './CloneMatrix';
import FetchingData     from './FetchingData';
import InitMatrix       from './InitMatrix';
import MatrixIsFull     from './MatrixIsFull';
import MergeAndShift    from './MergeAndShift';
import MoveTiles        from './MoveTiles';
import MergedtileObject from './MergedtileObject';
import NormaltileObject from './NormaltileObject';
import PickVirtualTiles from './PickVirtualTiles';
import PickRandomItems  from './pickRandomItems';
import AddToHistory     from './addToHistory';

export const print            = Print;
export const moveTiles        = MoveTiles;
export const initMatrix       = InitMatrix;
export const cloneMatrix      = CloneMatrix;
export const matrixIsFull     = MatrixIsFull;
export const fetchingData     = FetchingData;
export const mergeAndShift    = MergeAndShift;
export const addingNewTile    = AddingNewTile;
export const checkIfCanMerge   = CheckIfCanMerge;
export const mergedtileObject = MergedtileObject;
export const normaltileObject = NormaltileObject;
export const pickVirtualTiles = PickVirtualTiles;
export const pickRandomItems  = PickRandomItems;
export const addToHistory     = AddToHistory;